# NumPy OPerations

In [1]:
import numpy as np

## SLICING THE ARRAY

In [3]:
arr=np.arange(1,11)
print("Original Array" ,arr)
print("Basic Slicing" ,arr[2:7])
print("With steps" ,arr[1:8:2])
print("Negative Slicing" ,arr[-3])
print("Negative Slicing with End" ,arr[-3:])
print("Negative Slicing From Start" ,arr[:-3])

Original Array [ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing [3 4 5 6 7]
With steps [2 4 6 8]
Negative Slicing 8
Negative Slicing with End [ 8  9 10]
Negative Slicing From Start [1 2 3 4 5 6 7]


# Slice 2 D or n D array

In [5]:
arr2d=np.array([[3,1],[1,2],[2,3]])
print("Sorted Array By Column : ",np.sort(arr2d,axis=0))
print("Sorted Array By Row : ",np.sort(arr2d,axis=1))

Sorted Array By Column :  [[1 1]
 [2 2]
 [3 3]]
Sorted Array By Row :  [[1 3]
 [1 2]
 [2 3]]


# Filters

In [11]:
num=np.arange(1,11)
even=num[num%2==0]
print("Even Nos are : ",even)

# MASk (mask is the same expression as  FIller)

mask=(num%2)
print("Even Nos are Using Mask : ",num[mask==0])
mask=num>5
print("Num greater than '5' ",num[mask])

Even Nos are :  [ 2  4  6  8 10]
Even Nos are Using Mask :  [ 2  4  6  8 10]
Num greater than '5'  [ 6  7  8  9 10]


# np.where()

In [12]:
# Using Array from Above cell
indices=[0,1,4]
print(num[indices])
where_result=np.where(num>5)
print("Np where is used " ,num[where_result])


[1 2 5]
Np where is used  [ 6  7  8  9 10]


## ADD OR REMOVE ELEMENTS

In [17]:
arr=np.arange(1,5)
arr2=np.arange(4,8)
 # Performing Normal Addition 
add=arr+arr2
print("Addition of Two Arrays : ",add)

# Additing the elements into a single array 

conc=np.concatenate((arr,arr2))
print("COncated Array is : " ,conc)


Addition of Two Arrays :  [ 5  7  9 11]
COncated Array is :  [1 2 3 4 4 5 6 7]


# Compatibility of array 
check WHeter they are of same dimension or not

In [20]:
a=np.array([1,2,3])
b=np.array([4,4,4])
print("Check if compatible : " , a.shape==b.shape)

Check if compatible :  True


# Adding Row And COlumn

In [23]:
original=np.array([[1,2],[3,4],[5,6]])
new=np.array([5,6])
newC=np.array([[7],[8],[9]])
#Adding ROw using np.vstack
rowarr=np.vstack((original,new))
#Adding Column using np.hstack
coluarr=np.hstack((original,newC))
print("Original Array : ",original)
print("Row is added in Array : ",rowarr)
print("Column is added Array : ",coluarr)

Original Array :  [[1 2]
 [3 4]
 [5 6]]
Row is added in Array :  [[1 2]
 [3 4]
 [5 6]
 [5 6]]
Column is added Array :  [[1 2 7]
 [3 4 8]
 [5 6 9]]


# delete

In [25]:
delete=np.delete(original,2)
print("Array after deletion : ",delete)

Array after deletion :  [1 2 4 5 6]
