## Importing The Numpy 

In [ ]:
import numpy as np

# LIST VS ARRAY

In [ ]:
list=[1,2,3]
print("List : ", list)
arr1d=np.array([1,2,3])
print("Array : ", arr1d)
print("List multiplied by 2: ", list*2)
print("Array  Multiplied by 2: ",  arr1d*2)

# CREATING ARRAY FROM SCRATCH

In [ ]:

zeroarr=np.zeros([2,3])
print(zeroarr)
# ARRAY OF ONES
onesarr=np.ones([2,3])
print(onesarr)
# Array of Constants
const=np.full([2,3],8)
print(const)
# Array of Random Value
randomarr=np.random.random([2])
print(randomarr)

# MATRIX, ARRAY , TENSOR

In [ ]:
# array WIth Range 

arr2=np.arange(2,10,2)
print("Array : ", arr2)

#MATRIX  it is array of 2 dimension
mat=np.array([[1,2,3],[4,5,6]])
print("Matrix : ", mat)

# Tensor it is matrix of n dimension
ten=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("Tensor : ", ten)


Array :  [2 4 6 8]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# Properties of Array

In [9]:
arr=np.array([[1,2,3],[4,5,6]])
print("Original Array",arr)
print("Shape of Array",arr.shape)
print("Dimension of Array",arr.ndim)
print("Size of Array",arr.size)
print("Type of Array",arr.dtype)


Original Array [[1 2 3]
 [4 5 6]]
Shape of Array (2, 3)
Dimension of Array 2
Size of Array 6
Type of Array int64


# Reshaping The Array

In [12]:
# Making array using arange method
arr=np.arange(12)
print("Original Array : ",arr)

#Reshaping the array
reshape=arr.reshape((3,4))
print("Reshaped Array : ",reshape)

#Flattining The array (Makes Changes in Original Array)

flatten=reshape.flatten()
print("Flatten Array : ",flatten)

# Raveled (Flatten array and make changes in a copy)
raveled=reshape.ravel()
print("Raveled Array : ",raveled)

#Transpose Of array
trans=reshape.T
print("Transpose of Array : ",trans)

Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose of Array :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
