In [1]:
import numpy as np

# Practise the Questions of Numpy

1 Create a NumPy array from a Python list

[1, 2, 3, 4, 5]


2️⃣ Create a NumPy array of 10 zeros

3️⃣ Create a NumPy array of 10 ones

4️⃣ Create a NumPy array containing numbers from 5 to 50

5️⃣ Check the shape, dtype, and size of an array

In [2]:
# Q:1
arr1d=np.array([1,2,3,4,5])
print(arr1d)

[1 2 3 4 5]


In [3]:
# Q:2
zeroes=np.zeros(10)
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Q: 3
ones=np.ones(10)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
# Q : 4 
arr2=np.arange(5,51)
print(arr2)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [11]:
print(arr2.shape,arr2.ndim,arr2.size,arr2.dtype)

(46,) 1 46 int64


# Level 2

6️⃣ From this array:

arr = np.array([10, 20, 30, 40, 50])


Get the first element

Get the last element

Get elements [20, 30, 40]

7️⃣ From this array:

arr = np.arange(1, 11)


Get all even numbers

Get numbers greater than 5

In [12]:
arr=np.array([10,20,30,40,50])


In [14]:
# Q:6
print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]


In [18]:
# Q:7 
arr=np.arange(1,11)
even=arr[arr%2==0]
print(even)
mask=arr>5
print("Numbers Greater than 5 are " , arr[mask])

[ 2  4  6  8 10]
Numbers Greater than 5 are  [ 6  7  8  9 10]
